# Generated by Django 3.2.8 on 2021-10-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=200)),
                ('office_hours', models.CharField(max_length=20)),
            ],
        ),
    ]
