# Generated by Django 3.2.8 on 2021-11-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts_handbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_title', models.CharField(max_length=200)),
                ('rec_desc', models.TextField()),
                ('rec_main_image', models.ImageField(upload_to='')),
                ('rec_lil_image', models.ImageField(upload_to='')),
                ('rec_ingredients', models.TextField()),
                ('rec_receipt', models.TextField()),
                ('rec_category', models.CharField(max_length=200)),
                ('rec_cooktime', models.CharField(max_length=200)),
                ('rec_time_to_eat', models.CharField(max_length=200)),
                ('rec_calories', models.CharField(max_length=20)),
                ('rec_protein', models.CharField(max_length=20)),
                ('rec_fats', models.CharField(max_length=20)),
                ('rec_carbs', models.CharField(max_length=20)),
            ],
        ),
    ]
