# Generated by Django 3.2.8 on 2021-11-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts_handbook', '0002_recipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipt',
            name='rec_lil_image',
            field=models.ImageField(null=True, upload_to='receipts_handbook/modeld_files/main_images/'),
        ),
        migrations.AlterField(
            model_name='recipt',
            name='rec_main_image',
            field=models.ImageField(null=True, upload_to='receipts_handbook/modeld_files/main_images/'),
        ),
    ]
