# Generated by Django 3.2.8 on 2021-12-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts_handbook', '0004_auto_20211107_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.IntegerField()),
                ('cat_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nutri_val',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField()),
                ('carbons', models.FloatField()),
                ('fats', models.FloatField()),
                ('proteins', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='recipt',
            name='rec_cat_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='receipts_handbook.categories'),
        ),
        migrations.AddField(
            model_name='recipt',
            name='rec_nvals_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='receipts_handbook.nutri_val'),
        ),
    ]
